; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[ctools][version] = "1.3"

projects[context][version] = "3.0-beta6"

projects[devel][version] = "1.3"

projects[features][version] = "2.0-beta2"

projects[field_formatter_settings][version] = "1.0"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[masonry][version] = "1.1"

projects[multiupload_filefield_widget][version] = "1.11"

projects[multiupload_imagefield_widget][version] = "1.2"

projects[views][version] = "3.7"

projects[views_infinite_scroll][version] = "1.1"

; Themes
projects[bootstrap][version] = "2.0-beta3"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ddiboot][download][type] = "git"
projects[ddiboot][download][url] = "https://github.com/varunity/ddiboot.git"
projects[ddiboot][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[autopager][download][type] = "get"
libraries[autopager][download][url] = "http://jquery-autopager.googlecode.com/files/jquery.autopager-1.0.0.js"
libraries[autopager][directory_name] = "autopager"
libraries[autopager][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[masonry][download][type] = "get"
libraries[masonry][download][url] = "http://masonry.desandro.com/jquery.masonry.min.js"
libraries[masonry][directory_name] = "masonry"
libraries[masonry][type] = "library"


